FROM python:3.13-slim

RUN apt-get update && apt-get install -y \
    curl git nano exiftool \
    && rm -rf /var/lib/apt/lists/*

COPY . /app
WORKDIR /app

RUN pip install --no-cache-dir -r requirements.txt && \
    pip uninstall -y cmake


RUN ln -s /usr/bin/exiftool /usr/local/bin/exiftool


# Slim entrypoint (no Ollama startup)
COPY docker/entrypoint-slim.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
